services:
  bundlebox:
    build: .
    container_name: bundlebox
    ports:
      - "8100:8100"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
